# Generated by Django 5.1.6 on 2025-03-12 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reservation_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('active', 'Активна'), ('finished', 'Завершена'), ('overdue', 'Просрочена')], default='pending', max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('parkingzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.parkingzone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
