# Generated by Django 5.1.6 on 2025-03-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('active', 'Активна'), ('inside', 'На парковке'), ('finished', 'Завершена'), ('overdue', 'Просрочена')], default='pending', max_length=20),
        ),
    ]
