# Generated by Django 5.1.6 on 2025-03-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_parkingzone_latitude_parkingzone_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='barrier_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP шлагбаума'),
        ),
    ]
