# Generated by Django 5.2 on 2025-04-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_parkingzone_owner_user_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Паспортные данные'),
        ),
    ]
