# Generated by Django 5.2 on 2025-04-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Отображать парковку на сайте'),
        ),
    ]
