# Generated by Django 5.2 on 2025-05-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('individual', 'Частное лицо'), ('company', 'Компания')], max_length=255, null=True, verbose_name='Тип аккаунта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН компании'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
