# Generated by Django 5.2.1 on 2025-06-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_user_account_type_alter_user_inn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=32)),
                ('status', models.IntegerField(choices=[(0, 'Открыть'), (1, 'Открыть вручную'), (2, 'Закрыть')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
