# Generated by Django 5.2.1 on 2025-06-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_devicecommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='barrier_mac',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
